# Test

In [7]:
import pandas as pd

In [8]:
test_csv = pd.read_csv('./dataset/test.csv')
train_csv = pd.read_csv('./dataset/train.csv')
sample_csv = pd.read_csv('dataset/sample_submission.csv')

In [9]:
# train_csv.columns, 
train_csv.head(5)

,id,prompt,svg
0,fd61e324e0cec5c11f337d0bfe2858c8,The image features two orange squares with a m...,"<svg xmlns=""http://www.w3.org/2000/svg"" viewBo..."
1,999b3d4d5a860725bf9528910b5612f3,A simple smiley face with a wide open mouth an...,"<svg xmlns=""http://www.w3.org/2000/svg"" viewBo..."
2,1aaa84517819c25f783ae1c0cb337fc5,The image features a black-outlined icon of a ...,"<svg xmlns=""http://www.w3.org/2000/svg"" viewBo..."
3,919a7da8bd44dc7781dbe87383a268cc,The image displays a black icon with a photo-l...,"<svg xmlns=""http://www.w3.org/2000/svg"" viewBo..."
4,thesantatitan_deepseek-svg-dataset_0000581,Generate svg code for an image that looks like...,"<svg width=""24"" height=""24"" viewBox=""0 0 24 24..."

In [10]:
sample_csv.head(5)

,id,svg
0,fa1d8fa7-080f-4269-a9cf-a17562c9a0ca,<svg xmlns='http://www.w3.org/2000/svg' width=...
1,6eede943219547c22ac56085027d33cc,<svg xmlns='http://www.w3.org/2000/svg' width=...
2,ea045c7a247166f061ce504d9b7ccaab,<svg xmlns='http://www.w3.org/2000/svg' width=...
3,8fe82f3af89e487b31236ca829c3f071,<svg xmlns='http://www.w3.org/2000/svg' width=...
4,600464e4d92c75338462271a09b3f176,<svg xmlns='http://www.w3.org/2000/svg' width=...

In [11]:
test_csv.head(5)

,id,prompt
0,fa1d8fa7-080f-4269-a9cf-a17562c9a0ca,firewood stack cut logs wood with leaf illustr...
1,6eede943219547c22ac56085027d33cc,The image shows five horizontal lines of varyi...
2,ea045c7a247166f061ce504d9b7ccaab,A stylized icon depicting a curved arrow withi...
3,8fe82f3af89e487b31236ca829c3f071,The image contains black geometric shapes agai...
4,600464e4d92c75338462271a09b3f176,The image shows a single dark gray triangle po...

In [2]:
string_test = """
system
You generate compact, valid SVG markup from user requests. Return only SVG code with a single root <svg> element.
user
a square and a circle
assistant
<svg fill="none" height="128" viewBox="0 0 48 48" width="128" xmlns="http://www.w3.org/2000/svg"><path d="m24 16v-8h16v8zm0 0l-16 16 16 16z" stroke="#000000" stroke-linecap="round" stroke-linejoin="round"/></svg>
"""

In [ ]:
import re
import xml.etree.ElementTree as ET

SVG_REGEX = re.compile(r"<svg[\s\S]*?</svg>", flags=re.IGNORECASE)


def extract_svg(text):
    m = SVG_REGEX.search(text)
    return m.group(0).strip() if m else ""

In [3]:
extract_svg(string_test)

''